version: '3'
services:
  jenkins:
    privileged: true
    build:
      context: . 
      dockerfile: ./Dockerfile
    container_name: lerna_jenkins
    ports:
      - '8080:8080'
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      - S3_BUCKET=S3_BUCKET
      - AWS_ACCESS_KEY_ID=access_key
      - AWS_SECRET_ACCESS_KEY=secret
volumes:
  jenkins-data:
